sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq
  - sudo pip install cpp-coveralls

install:
  - sudo apt-get -y install qt57[QTPACKAGE]

script:
  - source /opt/qt57/bin/qt57-env.sh
  - qmake "CONFIG+=test" Testes/primitiveLibs/LinAlg/matrix/matrix.pro
  - make
  - ./tst_matrixtest

after_success:
- cpp-coveralls
  