sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq
  - sudo apt-get install libudunits2-dev lcov python-yaml
  - sudo pip install cpp-coveralls

install:
  - sudo apt-get -y install qt57[QTPACKAGE]

script:
  - source /opt/qt57/bin/qt57-env.sh
  - qmake "CONFIG+=test" Testes/primitiveLibs/LinAlg/matrix/matrix.pro
  - make
  - ./tst_matrixtest
  - qmake "CONFIG+=test" Testes/primitiveLibs/LinAlg/MatrixLongDouble/MatrixLongDouble.pro
  - make
  - ./tst_matrixlongdoubletest
  - qmake "CONFIG+=test" Testes/primitiveLibs/polynomDouble/polynomDouble.pro
  - make
  - ./tst_polynomdoubletest
- qmake "CONFIG+=test" Testes/primitiveLibs/LinAlg/LinAlg/LinAlg.pro
  - make
  - ./tst_linalgtest

after_success:
- cpp-coveralls  